apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seldon-prometheus-exporter.fullname" . }}
  labels:
    {{- include "seldon-prometheus-exporter.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "seldon-prometheus-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "seldon-prometheus-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "seldon-prometheus-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- if .Values.prometheus.url }}
            - name: "PROMETHEUS_URL"
              value: "{{ .Values.prometheus.url }}"
            {{- end}}
            {{- if .Values.timePeriod }}
            - name: "TIME_PERIOD"
              value: "{{ .Values.timePeriod }}"
            {{- end}}
            {{- if .Values.prometheus.jwtSecretName }}
            - name: "PROMETHEUS_SELDON_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.prometheus.seldon.jwtSecretName }}
                  key: {{ .Values.prometheus.seldon.jwtSecretKey }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
